# 根据API文档指定端口号
server:
  port: 9004 # 服务访问端口号

spring:
  application:
    # 服务名字
    name: tensquare-article
  # 配置数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.14.3:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: root
  data:
    # 配置mongodb
    mongodb:
      host: 192.168.14.3
      # port: 27017 默认端口号，可以省略
      database: commentdb # 数据库名字
  # 配置redis
  redis:
    host: 192.168.14.3
    # port: 6379 默认端口号，可以省略
  # 配置rabbitmq
  rabbitmq:
    host: 192.168.14.3

# mybatis-plus配置
mybatis-plus:
  # mapper-locations: classpath:/mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.tensquare.article.pojo
  global-config:
    id-type: 1  # 0：数据库ID自增  1：用户输入id
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true             # 配置缓存的全局开关
      lazyLoadingEnabled: true        # 延时加载的开关
      multipleResultSetsEnabled: true # 开启延时加载，否则按需加载属性
      # 打印sql语句，调试用
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置Eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    # 设置发现IP
    prefer-ip-address: true
